SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '%K' 

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____' 

SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE LASTNAME LIKE '_____A'

SELECT * FROM STUDENT WHERE LASTNAME LIKE '%TEL' 

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'HA%T' 

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'K_Y%' 

SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE is not  NULL AND FIRSTNAME LIKE '_____'  

SELECT * FROM STUDENT WHERE LASTNAME LIKE '%JER%' 

SELECT * FROM STUDENT WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'

SELECT * FROM STUDENT WHERE WEBSITE  IS NULL

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '[A-H]%'

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '[A,E,I,O,U]%'

SELECT FIRSTNAME FROM STUDENT WHERE CITY LIKE '%ROD%'

SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE WEBSITE LIKE 'BI%'

SELECT CITY FROM STUDENT WHERE LASTNAME LIKE '______'

SELECT * FROM STUDENT WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%'

SELECT * FROM STUDENT WHERE DIVISION LIKE 'II%'

SELECT FIRSTNAME FROM STUDENT WHERE DIVISION LIKE '%BC%'

SELECT STUID, CITY FROM STUDENT WHERE DIVISION LIKE '______' AND WEBSITE  IS not NULL