CREATE TABLE STUDENT_J
(
	RNO INT,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50)
)
INSERT INTO STUDENT_J VALUES(101,'RAJU','CE')
INSERT INTO STUDENT_J VALUES(102,'AMIT','CE')
INSERT INTO STUDENT_J VALUES(103,'SANJAY','ME')
INSERT INTO STUDENT_J VALUES(104,'NEHA','EC')
INSERT INTO STUDENT_J VALUES(105,'MEERA','EE')
INSERT INTO STUDENT_J VALUES(106,'MAHESH','ME')
SELECT * FROM STUDENT_J
UPDATE STUDENT_J SET BRANCH='EC' WHERE BRANCH='ME' AND NAME='NEHA'
CREATE TABLE RESULT_J
(
	RNO INT,
	SPI FLOAT
)
INSERT INTO RESULT_J VALUES(101,8.8)
INSERT INTO RESULT_J VALUES(102,9.2)
INSERT INTO RESULT_J VALUES(103,7.6)
INSERT INTO RESULT_J VALUES(104,8.2)
INSERT INTO RESULT_J VALUES(105,7.0)
INSERT INTO RESULT_J VALUES(107,8.9)

CREATE TABLE EMPLOYEE_J
(
	EMPLOYEENO VARCHAR(50),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(50)
)
INSERT INTO EMPLOYEE_J VALUES('E01','TARUN',NULL)
INSERT INTO EMPLOYEE_J VALUES ('E02','ROHAN','E02')
INSERT INTO EMPLOYEE_J VALUES ('E03','PRIYA','E01')
INSERT INTO EMPLOYEE_J VALUES('E04','MILAN','E03')
INSERT INTO EMPLOYEE_J VALUES('E05','JAY','E01')
INSERT INTO EMPLOYEE_J VALUES('E06', 'ANJANA','E04')

-1-
SELECT * FROM STUDENT_J CROSS JOIN RESULT_J

-2-
SELECT
	STUDENT_J.RNO,
	STUDENT_J.NAME,
	STUDENT_J.BRANCH,
	RESULT_J.SPI
FROM STUDENT_J
INNER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO
WHERE STUDENT_J.BRANCH='CE'


-3-
SELECT
	STUDENT_J.RNO,
	STUDENT_J.NAME,
	STUDENT_J.BRANCH,
	RESULT_J.SPI
FROM STUDENT_J
INNER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO
WHERE STUDENT_J.BRANCH<>'EC'

-4-
SELECT
	AVG(RESULT_J.SPI),
	STUDENT_J.BRANCH
FROM STUDENT_J
INNER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO
GROUP BY BRANCH

-5-
SELECT
	AVG(RESULT_J.SPI),
	STUDENT_J.BRANCH
FROM STUDENT_J
INNER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO
GROUP BY STUDENT_J.BRANCH
ORDER BY AVG(RESULT_J.SPI) 

-6-
SELECT
	AVG(RESULT_J.SPI),
	STUDENT_J.BRANCH
FROM STUDENT_J
INNER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO
WHERE STUDENT_J.BRANCH='CE' 
GROUP BY STUDENT_J.BRANCH

SELECT
	STUDENT_J.Branch,
	AVG(Result_J.SPI) As Avg_Spi
FROM STUDENT_J
INNER JOIN RESULT_J
ON Student_J.Rno = RESULT_J.Rno
AND (Studen_J.Branch IN ('CE','ME'))
GROUP BY STUDENT_J.Branch

-7-
SELECT * FROM STUDENT_J LEFT OUTER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO

-8-
SELECT * FROM STUDENT_J RIGHT OUTER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO

-9-
SELECT * FROM STUDENT_J FULL OUTER JOIN RESULT_J
ON STUDENT_J.RNO=RESULT_J.RNO

-10-