CREATE TABLE STUDENTS 
( 
RNO INT, 
NAME VARCHAR(50), 
CITY VARCHAR(50), 
DID INT 
); 
CREATE TABLE ACADEMIC 
( 
RNO INT, 
SPI DECIMAL(4,2), 
BKLOG INT 
); 
CREATE TABLE DEPARTMENT 
( 
DID INT, 
DNAME VARCHAR(50) 
); 

INSERT INTO STUDENTS VALUES(101,'RAJU','RAJKOT',10); 
INSERT INTO STUDENTS VALUES(102,'AMIT','AHMEDABAD',20); 
INSERT INTO STUDENTS VALUES(103,'SANJAY','BARODA',40); 
INSERT INTO STUDENTS VALUES(104,'NEHA','RAJKOT',20); 
INSERT INTO STUDENTS VALUES(105,'MEERA','AHMEDABAD',30); 
INSERT INTO STUDENTS VALUES(106,'MAHESH','BARODA',10); 
INSERT INTO ACADEMIC VALUES(101,8.8,0); 
INSERT INTO ACADEMIC VALUES(102,9.2,2); 
INSERT INTO ACADEMIC VALUES(103,7.6,1); 
INSERT INTO ACADEMIC VALUES(104,8.2,4); 
INSERT INTO ACADEMIC VALUES(105,7.0,2); 
INSERT INTO ACADEMIC VALUES(106,8.9,3); 
INSERT INTO DEPARTMENT VALUES(10,'COMPUTER'); 
INSERT INTO DEPARTMENT VALUES(20,'ELECTRICAL'); 
INSERT INTO DEPARTMENT VALUES(30,'MECHANICAL'); 
INSERT INTO DEPARTMENT VALUES(40,'CIVIL'); 



SELECT*FROM STUDENTS WHERE DID IN
(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER')

SELECT NAME FROM STUDENTS WHERE RNO IN
(SELECT RNO FROM ACADEMIC WHERE SPI>8)

SELECT *FROM STUDENTS WHERE CITY='RAJKOT' AND DID IN
(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER')

SELECT COUNT(*) FROM STUDENTS WHERE DID IN 
(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')

SELECT NAME 

