CREATE TABLE Student1 
( 
RNo INT NOT NULL, 
Name VARCHAR(50) NOT NULL, 
Branch VARCHAR(50) NOT NULL 
); 
CREATE TABLE Result 
( 
RNo INT NOT NULL, 
SPI Decimal(5,2) NOT NULL 
); 
INSERT INTO Student1 VALUES (101,'RAJU','CE') 
INSERT INTO Student1 VALUES (102,'AMIT','CE') 
INSERT INTO Student1 VALUES (103,'SANJAY','ME') 
INSERT INTO Student1 VALUES (104,'NEHA','EC') 
INSERT INTO Student1 VALUES (105,'MEERA','EE') 
INSERT INTO Student1 VALUES (106,'MAHESH','ME') 

INSERT INTO Result VALUES (101,8.8) 
INSERT INTO Result VALUES (102,9.2) 
INSERT INTO Result VALUES (103,7.6) 
INSERT INTO Result VALUES (104,8.2) 
INSERT INTO Result VALUES (105,7.0) 
INSERT INTO Result VALUES (105,8.9) 

CREATE PROCEDURE STUDENT1_DETAILS
AS
BEGIN
SELECT Student.RNo,Student1.Name,Student.Branch,Result.SPI
FROM Student INNER JOIN Result
ON STUDENT.RNO=Result.RNo
END
EXEC STUDENT_DETAILS



CREATE PROCEDURE STUDENT_DETAILSBYRNO
@RNO INT
AS
BEGIN
SELECT Student.RNo,Student.Name,Student.Branch,Result.SPI
FROM Student INNER JOIN Result
ON STUDENT.RNO=Result.RNo
WHERE STUDENT.RNO=@RNO
END
EXEC STUDENT_DETAILSBYRNO 102



CREATE PROCEDURE INSERTDATA
@RNO INT,
@NAME VARCHAR(50),
@BRANCH VARCHAR(50)
AS
BEGIN
INSERT INTO STUDENT
VALUES(@RNO,@NAME,@BRANCH)
END
EXEC INSERTDATA 107,'RAJ','EE'


CREATE PROCEDURE UPDATEDATA
@RNO INT,
@BRANCH VARCHAR(50)
AS
BEGIN
UPDATE Student
SET @BRANCH='EC'
WHERE @RNO=105
END
EXEC UPDATEDATA

