CREATE TABLE EMPLOYEE
(
	EID INT,
	ENAME VARCHAR(50),
	DEPARTMENT VARCHAR(50),
	SALARY DECIMAL(8,2),
	JOININGDATE DATETIME,
	CITY VARCHAR(50),


)
INSERT INTO EMPLOYEE VALUES(101,'RAHUL','ADMIN',56000,'1990-01-01','RAJKOT')
INSERT INTO EMPLOYEE VALUES(102,'HARDIK','IT',18000,'1990-09-25','AHMEDABAD')
INSERT INTO EMPLOYEE VALUES(103,'BHAVIN','HR',25000,'1991-05-14','BARODA')
INSERT INTO EMPLOYEE VALUES(104,'BHOOMI','ADMIN',39000,'1991-02-08','RAJKOT')
INSERT INTO EMPLOYEE VALUES(105,'ROHIT','IT',17000,'1990-06-23','JAMNAGER')
INSERT INTO EMPLOYEE VALUES(106,'PRIYA','IT',9000,'1990-10-18','AHMEDBAD')
INSERT INTO EMPLOYEE VALUES(107,'NEHA', 'HR', 34000, '1991-12-25', 'RAJKOT')
DELETE FROM EMPLOYEE WHERE EID=107
SELECT * FROM EMPLOYEE

SELECT MAX(SALARY) AS MAXIMUM,
		MIN(SALARY) AS MINIMUM,
		SUM(SALARY) AS TOTAL_SAL,
		AVG(SALARY) AS AVERAGE_SAL
		FROM EMPLOYEE

SELECT COUNT(ENAME) FROM EMPLOYEE

SELECT DEPARTMENT,MAX(SALARY) AS MAXIMUM
 FROM EMPLOYEE
  WHERE DEPARTMENT='IT' 
  GROUP BY DEPARTMENT

SELECT COUNT(DISTINCT CITY) AS UNIQUE_CITY FROM EMPLOYEE

SELECT CITY, COUNT(*) AS TOTAL_EMP
FROM EMPLOYEE
GROUP BY CITY

SELECT CITY, COUNT(*) AS TOTAL_EMP
FROM EMPLOYEE
GROUP BY CITY
HAVING COUNT(*)>1

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SAL
FROM EMPLOYEE
GROUP BY DEPARTMENT

SELECT AVG(SALARY) AS AVERAGE
FROM EMPLOYEE
GROUP BY DEPARTMENT

SELECT MIN(SALARY) AS MINIMUM
FROM EMPLOYEE
WHERE CITY='AHMEDABAD'

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SAL
FROM EMPLOYEE
WHERE CITY='RAJKOT'
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>50000

SELECT COUNT(*) AS TOTAL_EMP
FROM EMPLOYEE
WHERE CITY='RAJKOT'

SELECT MAX(SALARY)-MIN(SALARY) AS SAL_DIFFERNCE
FROM EMPLOYEE

SELECT COUNT(*)AS TOTAL_EMP 
FROM EMPLOYEE
WHERE JOININGDATE<'1991-01-01'

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>35000
ORDER BY SUM(SALARY)

SELECT DEPARTMENT, COUNT(*) AS TOTAL_EMP
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*)>2

SELECT MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEE
WHERE CITY='RAJKOT'

SELECT CITY, COUNT(*)AS TOTAL_EMP
FROM EMPLOYEE
GROUP BY CITY

SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT

SELECT SUM(SALARY)AS TOTAL_SAL
FROM EMPLOYEE
GROUP BY CITY

SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY,
					MAX(SALARY) AS MAX_SALARY,
					SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT

SELECT CITY, DEPARTMENT, MAX(SALARY)AS MAX_SALARY, MIN(SALARY)AS MIN_SALARY
FROM EMPLOYEE
GROUP BY CITY, DEPARTMENT
HAVING MIN(SALARY)<30000