CREATE TABLE STUDENTS2
(
	 RNO INT,
	 NAME VARCHAR(50),
	 BRANCH VARCHAR(50),
	 SPI DECIMAL(4,2),
	 BKLOG INT
);
INSERT INTO STUDENTS2 VALUES(106,'MAHESH','EC',4.50,3)

-1-
CREATE VIEW PERSONAL 
AS
SELECT * FROM STUDENTS2

SELECT * FROM PERSONAL

-2-
CREATE VIEW STUDENT_DETAILS2
AS
SELECT NAME, BRANCH,SPI FROM STUDENTS2 

SELECT * FROM STUDENT_DETAILS2

-3-
CREATE VIEW ACADEMIC
AS
SELECT RNO,NAME,Branch FROM STUDENTS2

SELECT * FROM ACADEMIC

-4-
CREATE VIEW STUDENT_DATA
AS
SELECT * FROM STUDENTS2 
WHERE BKLOG>2

SELECT * FROM STUDENT_DATA

-5-
CREATE VIEW STUDENT_PATTERN
AS
SELECT RNO,NAME,BRANCH FROM STUDENTS2
WHERE NAME LIKE '____'

SELECT * FROM STUDENT_PATTERN

-6-
INSERT INTO ACADEMIC VALUES (107,'MEET','ME')

SELECT * FROM ACADEMIC

-7-
UPDATE STUDENT_DETAILS SET BRANCH='ME' WHERE BRANCH='CE' AND NAME='AMIT'

SELECT * FROM STUDENT_DETAILS

-8-
DELETE FROM ACADEMIC WHERE RNO=104


SELECT * FROM ACADEMIC

-9-
CREATE VIEW V1
AS
SELECT * FROM STUDENTS
WHERE SPI>9.5

SELECT * FROM V1

-10-
CREATE VIEW V2
AS
SELECT * FROM STUDENTS
WHERE BKLOG=0

SELECT * FROM V2