	select len(null)
	select len('hello')
	select len('')

	SELECT LOWER('TISHA')
	SELECT UPPER('TISHA')

	SELECT SUBSTRING('TISHA',1,3)

	SELECT SUBSTRING('TISHA',3,10)

	SELECT REPLACE('ABC123EFG','123','XYZ')
	SELECT REPLACE('ABCABCABC','C','5')

	SELECT ASCII('a')
	SELECT ASCII('A')
	SELECT ASCII('z')
	SELECT ASCII('Z')
	SELECT ASCII(0)
	SELECT ASCII(9)

	SELECT CHAR(97)
	SELECT CHAR(122)
	SELECT CHAR(65)
	SELECT CHAR(90)
	SELECT CHAR(48)
	SELECT CHAR(57)

	SELECT LTRIM('HELLO WORLD     ')
	SELECT RTRIM('HELLO WORLD')

	SELECT LEFT('SQL SERVER',4)
	SELECT RIGHT('SQL SERVER',5)

	SELECT CAST('1234.56' AS float)
	SELECT CONVERT(INT,10.58)

	SELECT SPACE(10)+'TISHA'

	SELECT 'TISHA'+'MEHTA'
	SELECT CONCAT('TISHA','MEHTA')

	SELECT REVERSE('DARSHAN')

	SELECT REPLICATE('TISHA',3)

	Select STUFF ('SQL Tutorial',1,3,'HTML')

	SELECT COALESCE(NULL,NULL,'TISHA')
	SELECT COALESCE(NULL,'TISHA','MEHTA')

	SELECT ISNUMERIC('TISHA')
	SELECT ISNUMERIC(123)

	SELECT CHARINDEX('T','CUSTOMER')