CREATE TABLE STUDENT_S
(
	RNO INT,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50)
);
INSERT INTO STUDENT_S VALUES(101,'RAJU','CE')

INSERT INTO STUDENT_S VALUES(102,'AMIT','CE')

INSERT INTO STUDENT_S VALUES(103,'SANJAY','ME')

INSERT INTO STUDENT_S VALUES(104,'NEHA','EC')

INSERT INTO STUDENT_S VALUES(105,'MEERA','EE')

INSERT INTO STUDENT_S VALUES(106,'MAHESH','ME')

CREATE TABLE RESULT
(
	RNO INT,
	SPI DECIMAL(4,2)
);

INSERT INTO RESULT VALUES(101,8.8)
INSERT INTO RESULT VALUES(102,9.2)
INSERT INTO RESULT VALUES(103,7.6)
INSERT INTO RESULT VALUES(104,8.2)
INSERT INTO RESULT VALUES(105,7.0)
INSERT INTO RESULT VALUES(106,8.9)
